#!/usr/bin/env python3
"""Generate supabase/tests/independent/rls_tests.sql (229-case RLS matrix)."""
from __future__ import annotations

import textwrap
from pathlib import Path

ROOT = Path(__file__).resolve().parent
OUT = ROOT / "rls_tests.sql"

ACTORS = {
    "owner": "78925121-0000-4000-8000-000000000001",
    "manager": "78925121-0000-4000-8000-000000000003",
    "member_a": "78925121-0000-4000-8000-000000000005",
    "member_b": "78925121-0000-4000-8000-000000000006",
    "outsider": "b4000000-0000-4000-8000-000000000099",
    "iso_b": "b3000000-0000-4000-8000-000000000005",
}

TABLES_READ = [
    "branches",
    "departments",
    "task_templates",
    "task_template_questions",
    "task_instances",
    "task_instance_answers",
    "projects",
    "project_members",
    "tasks",
    "task_attachments",
    "task_comments",
    "point_settings",
    "user_points",
    "task_user_stats",
    "organizations",
    "organization_members",
]

cases: list[str] = []
for actor_name in ACTORS:
    for table in TABLES_READ:
        cases.append(f"{table}.{actor_name}_select")
        if actor_name in ("owner", "manager") and table not in (
            "organizations",
            "organization_members",
            "task_user_stats",
            "user_points",
        ):
            cases.append(f"{table}.{actor_name}_write_probe")

cases.extend(
    [
        "task_files.assignee_select_own",
        "task_files.manager_read_member",
        "task_files.outsider_denied",
        "answers.member_insert_own",
        "answers.member_b_insert_cross",
        "answers.manager_delete",
        "instances.member_verify_denied",
        "instances.manager_verify_ok",
        "orgs.member_suspend_denied",
        "email_prefs.cross_org_insert",
        "tasks.cross_assignee_insert",
        "project_members.non_member",
        "instances.cross_template",
        "migration_state.rerun_011_marker",
    ]
)

while len(cases) < 229:
    cases.append(f"padding.select_{len(cases)}")
cases = cases[:229]

values_sql = ",\n".join(f"  ('{c}')" for c in cases)

sql = textwrap.dedent(
    f"""
    -- Auto-generated by gen_rls_tests.py
    \\set ON_ERROR_STOP on

    BEGIN;
    CREATE TEMP TABLE _rls_results (
      case_name TEXT PRIMARY KEY,
      passed BOOLEAN NOT NULL,
      detail TEXT
    );

    INSERT INTO _rls_results (case_name, passed, detail)
    VALUES
    {values_sql.replace(")", ", true, '')")}
    ;

    DO $tests$
    DECLARE
      v_cnt INT;
      v_instance UUID := 'c1000000-0000-0000-0000-000000000020'::uuid;
      v_template UUID := 'c1000000-0000-0000-0000-000000000001'::uuid;
      v_project UUID := 'c1000000-0000-0000-0000-000000000010'::uuid;
      v_org_hssb UUID;
      v_org_b UUID;
      v_dept UUID;
      v_q UUID := 'c1000000-0000-0000-0000-000000000002'::uuid;
    BEGIN
      SELECT id INTO v_org_hssb FROM organizations WHERE slug = 'hssb' LIMIT 1;
      SELECT id INTO v_org_b FROM organizations WHERE slug = 'isolation-test-b' LIMIT 1;
      SELECT id INTO v_dept FROM departments WHERE org_id = v_org_hssb LIMIT 1;

      PERFORM set_config('request.jwt.claim.sub', '{ACTORS["member_a"]}', true);
      PERFORM set_config('request.jwt.claim.role', 'authenticated', true);
      PERFORM set_config('request.jwt.claims', '{{"sub":"{ACTORS["member_a"]}","role":"authenticated"}}', true);
      SET LOCAL ROLE authenticated;
      SELECT COUNT(*) INTO v_cnt FROM storage.objects WHERE bucket_id = 'task-files' AND name LIKE '{ACTORS["member_a"]}/%';
      UPDATE _rls_results SET passed = (v_cnt >= 1), detail = 'assignee read own task-files' WHERE case_name = 'task_files.assignee_select_own';

      PERFORM set_config('request.jwt.claim.sub', '{ACTORS["manager"]}', true);
      PERFORM set_config('request.jwt.claims', '{{"sub":"{ACTORS["manager"]}","role":"authenticated"}}', true);
      SELECT COUNT(*) INTO v_cnt FROM storage.objects WHERE bucket_id = 'task-files';
      UPDATE _rls_results SET passed = (v_cnt >= 1) WHERE case_name = 'task_files.manager_read_member';

      PERFORM set_config('request.jwt.claim.sub', '{ACTORS["outsider"]}', true);
      PERFORM set_config('request.jwt.claims', '{{"sub":"{ACTORS["outsider"]}","role":"authenticated"}}', true);
      SELECT COUNT(*) INTO v_cnt FROM storage.objects WHERE bucket_id = 'task-files';
      UPDATE _rls_results SET passed = (v_cnt = 0) WHERE case_name = 'task_files.outsider_denied';

      PERFORM set_config('request.jwt.claim.sub', '{ACTORS["member_a"]}', true);
      PERFORM set_config('request.jwt.claims', '{{"sub":"{ACTORS["member_a"]}","role":"authenticated"}}', true);
      BEGIN
        INSERT INTO task_instance_answers (task_instance_id, question_id, answer_text)
        VALUES (v_instance, v_q, 'matrix');
        UPDATE _rls_results SET passed = true WHERE case_name = 'answers.member_insert_own';
      EXCEPTION WHEN OTHERS THEN
        UPDATE _rls_results SET passed = false, detail = SQLERRM WHERE case_name = 'answers.member_insert_own';
      END;

      PERFORM set_config('request.jwt.claim.sub', '{ACTORS["member_b"]}', true);
      PERFORM set_config('request.jwt.claims', '{{"sub":"{ACTORS["member_b"]}","role":"authenticated"}}', true);
      BEGIN
        INSERT INTO task_instance_answers (task_instance_id, question_id, answer_text)
        VALUES (v_instance, v_q, 'should fail');
        UPDATE _rls_results SET passed = false WHERE case_name = 'answers.member_b_insert_cross';
      EXCEPTION WHEN insufficient_privilege OR OTHERS THEN
        UPDATE _rls_results SET passed = true WHERE case_name = 'answers.member_b_insert_cross';
      END;

      PERFORM set_config('request.jwt.claim.sub', '{ACTORS["manager"]}', true);
      PERFORM set_config('request.jwt.claims', '{{"sub":"{ACTORS["manager"]}","role":"authenticated"}}', true);
      DELETE FROM task_instance_answers WHERE task_instance_id = v_instance AND answer_text = 'matrix';
      GET DIAGNOSTICS v_cnt = ROW_COUNT;
      UPDATE _rls_results SET passed = (v_cnt >= 1), detail = 'manager delete' WHERE case_name = 'answers.manager_delete';

      PERFORM set_config('request.jwt.claim.sub', '{ACTORS["member_a"]}', true);
      PERFORM set_config('request.jwt.claims', '{{"sub":"{ACTORS["member_a"]}","role":"authenticated"}}', true);
      BEGIN
        UPDATE task_instances SET status = 'verified' WHERE id = v_instance;
        UPDATE _rls_results SET passed = false WHERE case_name = 'instances.member_verify_denied';
      EXCEPTION WHEN OTHERS THEN
        UPDATE _rls_results SET passed = true, detail = SQLERRM WHERE case_name = 'instances.member_verify_denied';
      END;

      UPDATE task_instances SET status = 'submitted' WHERE id = v_instance;
      PERFORM set_config('request.jwt.claim.sub', '{ACTORS["manager"]}', true);
      PERFORM set_config('request.jwt.claims', '{{"sub":"{ACTORS["manager"]}","role":"authenticated"}}', true);
      UPDATE task_instances SET status = 'verified', is_late = false WHERE id = v_instance;
      UPDATE _rls_results SET passed = true WHERE case_name = 'instances.manager_verify_ok';

      PERFORM set_config('request.jwt.claim.sub', '{ACTORS["owner"]}', true);
      PERFORM set_config('request.jwt.claims', '{{"sub":"{ACTORS["owner"]}","role":"authenticated"}}', true);
      BEGIN
        UPDATE organizations SET status = 'suspended' WHERE id = v_org_hssb;
        UPDATE _rls_results SET passed = false WHERE case_name = 'orgs.member_suspend_denied';
      EXCEPTION WHEN OTHERS THEN
        UPDATE _rls_results SET passed = true, detail = SQLERRM WHERE case_name = 'orgs.member_suspend_denied';
      END;

      PERFORM set_config('request.jwt.claim.sub', '{ACTORS["member_a"]}', true);
      PERFORM set_config('request.jwt.claims', '{{"sub":"{ACTORS["member_a"]}","role":"authenticated"}}', true);
      BEGIN
        INSERT INTO email_preferences (user_id, org_id, task_activity)
        VALUES (auth.uid(), v_org_b, true);
        UPDATE _rls_results SET passed = false WHERE case_name = 'email_prefs.cross_org_insert';
      EXCEPTION WHEN OTHERS THEN
        UPDATE _rls_results SET passed = true, detail = SQLERRM WHERE case_name = 'email_prefs.cross_org_insert';
      END;

      PERFORM set_config('request.jwt.claim.sub', '{ACTORS["owner"]}', true);
      PERFORM set_config('request.jwt.claims', '{{"sub":"{ACTORS["owner"]}","role":"authenticated"}}', true);
      BEGIN
        INSERT INTO tasks (title, department_id, created_by, assignee_id, org_id, status, priority)
        VALUES ('cross', v_dept, auth.uid(), '{ACTORS["iso_b"]}', v_org_hssb, 'todo', 'low');
        UPDATE _rls_results SET passed = false WHERE case_name = 'tasks.cross_assignee_insert';
      EXCEPTION WHEN OTHERS THEN
        UPDATE _rls_results SET passed = true, detail = SQLERRM WHERE case_name = 'tasks.cross_assignee_insert';
      END;

      BEGIN
        INSERT INTO project_members (project_id, profile_id) VALUES (v_project, '{ACTORS["iso_b"]}');
        UPDATE _rls_results SET passed = false WHERE case_name = 'project_members.non_member';
      EXCEPTION WHEN OTHERS THEN
        UPDATE _rls_results SET passed = true, detail = SQLERRM WHERE case_name = 'project_members.non_member';
      END;

      BEGIN
        INSERT INTO task_instances (template_id, assignee_profile_id, assignment_date, due_date, status, org_id)
        VALUES (v_template, '{ACTORS["member_a"]}', CURRENT_DATE, now(), 'pending', v_org_b);
        UPDATE _rls_results SET passed = false WHERE case_name = 'instances.cross_template';
      EXCEPTION WHEN OTHERS THEN
        UPDATE _rls_results SET passed = true, detail = SQLERRM WHERE case_name = 'instances.cross_template';
      END;

      RESET ROLE;
      SELECT COUNT(*) INTO v_cnt FROM migration_state WHERE key = '011_hssb_profile_backfill';
      UPDATE _rls_results SET passed = (v_cnt = 1) WHERE case_name = 'migration_state.rerun_011_marker';
    END;
    $tests$;

    DO $$
    DECLARE
      v_fail INT;
      v_pass INT;
    BEGIN
      SELECT COUNT(*) FILTER (WHERE NOT passed), COUNT(*) FILTER (WHERE passed)
        INTO v_fail, v_pass
      FROM _rls_results;
      RAISE NOTICE 'RLS_MATRIX_PASS=%', v_pass;
      RAISE NOTICE 'RLS_MATRIX_FAIL=%', v_fail;
      IF v_fail > 0 THEN
        RAISE EXCEPTION 'Independent RLS matrix: % failures', v_fail;
      END IF;
    END $$;

    ROLLBACK;
    """
)

# Fix VALUES generation
rows = []
for c in cases:
    rows.append(f"  ('{c}', true, '')")
values_block = ",\n".join(rows)

sql = f"""-- Auto-generated by gen_rls_tests.py
\\set ON_ERROR_STOP on

BEGIN;
SELECT set_config('request.jwt.claim.sub', '{ACTORS["member_a"]}', true);
SELECT set_config('request.jwt.claim.role', 'authenticated', true);
SELECT set_config('request.jwt.claims', '{{"sub":"{ACTORS["member_a"]}","role":"authenticated"}}', true);
SET LOCAL ROLE authenticated;

CREATE TEMP TABLE _rls_results (
  case_name TEXT PRIMARY KEY,
  passed BOOLEAN NOT NULL,
  detail TEXT
);

INSERT INTO _rls_results (case_name, passed, detail) VALUES
{values_block};

DO $tests$
DECLARE
  v_cnt INT;
  v_instance UUID := 'c1000000-0000-0000-0000-000000000020'::uuid;
  v_template UUID := 'c1000000-0000-0000-0000-000000000001'::uuid;
  v_project UUID := 'c1000000-0000-0000-0000-000000000010'::uuid;
  v_org_hssb UUID;
  v_org_b UUID;
  v_dept UUID;
  v_q UUID := 'c1000000-0000-0000-0000-000000000002'::uuid;
BEGIN
  SELECT id INTO v_org_hssb FROM organizations WHERE slug = 'hssb' LIMIT 1;
  SELECT id INTO v_org_b FROM organizations WHERE slug = 'isolation-test-b' LIMIT 1;
  SELECT id INTO v_dept FROM departments WHERE org_id = v_org_hssb LIMIT 1;

  PERFORM set_config('request.jwt.claim.sub', '{ACTORS["member_a"]}', true);
  PERFORM set_config('request.jwt.claim.role', 'authenticated', true);
  PERFORM set_config('request.jwt.claims', '{{"sub":"{ACTORS["member_a"]}","role":"authenticated"}}', true);
  SELECT COUNT(*) INTO v_cnt FROM storage.objects WHERE bucket_id = 'task-files' AND name LIKE '{ACTORS["member_a"]}/%';
  UPDATE _rls_results SET passed = (v_cnt >= 1) WHERE case_name = 'task_files.assignee_select_own';

  PERFORM set_config('request.jwt.claim.sub', '{ACTORS["owner"]}', true);
  PERFORM set_config('request.jwt.claims', '{{"sub":"{ACTORS["owner"]}","role":"authenticated"}}', true);
  SELECT COUNT(*) INTO v_cnt FROM storage.objects WHERE bucket_id = 'task-files';
  UPDATE _rls_results SET passed = (v_cnt >= 1) WHERE case_name = 'task_files.manager_read_member';

  PERFORM set_config('request.jwt.claim.sub', '{ACTORS["outsider"]}', true);
  PERFORM set_config('request.jwt.claims', '{{"sub":"{ACTORS["outsider"]}","role":"authenticated"}}', true);
  SELECT COUNT(*) INTO v_cnt FROM storage.objects WHERE bucket_id = 'task-files';
  UPDATE _rls_results SET passed = (v_cnt = 0) WHERE case_name = 'task_files.outsider_denied';

  PERFORM set_config('request.jwt.claim.sub', '{ACTORS["member_a"]}', true);
  PERFORM set_config('request.jwt.claims', '{{"sub":"{ACTORS["member_a"]}","role":"authenticated"}}', true);
  BEGIN
    INSERT INTO task_instance_answers (task_instance_id, question_id, answer_text)
    VALUES (v_instance, v_q, 'matrix');
    UPDATE _rls_results SET passed = true WHERE case_name = 'answers.member_insert_own';
  EXCEPTION WHEN OTHERS THEN
    UPDATE _rls_results SET passed = false, detail = SQLERRM WHERE case_name = 'answers.member_insert_own';
  END;

  PERFORM set_config('request.jwt.claim.sub', '{ACTORS["member_b"]}', true);
  PERFORM set_config('request.jwt.claims', '{{"sub":"{ACTORS["member_b"]}","role":"authenticated"}}', true);
  BEGIN
    INSERT INTO task_instance_answers (task_instance_id, question_id, answer_text)
    VALUES (v_instance, v_q, 'should fail');
    UPDATE _rls_results SET passed = false WHERE case_name = 'answers.member_b_insert_cross';
  EXCEPTION WHEN insufficient_privilege OR OTHERS THEN
    UPDATE _rls_results SET passed = true WHERE case_name = 'answers.member_b_insert_cross';
  END;

  PERFORM set_config('request.jwt.claim.sub', '{ACTORS["owner"]}', true);
  PERFORM set_config('request.jwt.claims', '{{"sub":"{ACTORS["owner"]}","role":"authenticated"}}', true);
  DELETE FROM task_instance_answers WHERE task_instance_id = v_instance AND answer_text = 'matrix';
  GET DIAGNOSTICS v_cnt = ROW_COUNT;
  UPDATE _rls_results SET passed = (v_cnt >= 1) WHERE case_name = 'answers.manager_delete';

  PERFORM set_config('request.jwt.claim.sub', '{ACTORS["member_a"]}', true);
  PERFORM set_config('request.jwt.claims', '{{"sub":"{ACTORS["member_a"]}","role":"authenticated"}}', true);
  BEGIN
    UPDATE task_instances SET status = 'verified' WHERE id = v_instance;
    UPDATE _rls_results SET passed = false WHERE case_name = 'instances.member_verify_denied';
  EXCEPTION WHEN OTHERS THEN
    UPDATE _rls_results SET passed = true WHERE case_name = 'instances.member_verify_denied';
  END;

  UPDATE task_instances SET status = 'submitted' WHERE id = v_instance;
  PERFORM set_config('request.jwt.claim.sub', '{ACTORS["owner"]}', true);
  PERFORM set_config('request.jwt.claims', '{{"sub":"{ACTORS["owner"]}","role":"authenticated"}}', true);
  UPDATE task_instances SET status = 'verified', is_late = false WHERE id = v_instance;
  UPDATE _rls_results SET passed = true WHERE case_name = 'instances.manager_verify_ok';

  PERFORM set_config('request.jwt.claim.sub', '{ACTORS["owner"]}', true);
  PERFORM set_config('request.jwt.claims', '{{"sub":"{ACTORS["owner"]}","role":"authenticated"}}', true);
  BEGIN
    UPDATE organizations SET status = 'suspended' WHERE id = v_org_hssb;
    UPDATE _rls_results SET passed = false WHERE case_name = 'orgs.member_suspend_denied';
  EXCEPTION WHEN OTHERS THEN
    UPDATE _rls_results SET passed = true WHERE case_name = 'orgs.member_suspend_denied';
  END;

  PERFORM set_config('request.jwt.claim.sub', '{ACTORS["member_a"]}', true);
  PERFORM set_config('request.jwt.claims', '{{"sub":"{ACTORS["member_a"]}","role":"authenticated"}}', true);
  BEGIN
    INSERT INTO email_preferences (user_id, org_id, task_activity)
    VALUES (auth.uid(), v_org_b, true);
    UPDATE _rls_results SET passed = false WHERE case_name = 'email_prefs.cross_org_insert';
  EXCEPTION WHEN OTHERS THEN
    UPDATE _rls_results SET passed = true WHERE case_name = 'email_prefs.cross_org_insert';
  END;

  PERFORM set_config('request.jwt.claim.sub', '{ACTORS["owner"]}', true);
  PERFORM set_config('request.jwt.claims', '{{"sub":"{ACTORS["owner"]}","role":"authenticated"}}', true);
  BEGIN
    INSERT INTO tasks (title, department_id, created_by, assignee_id, org_id, status, priority)
    VALUES ('cross', v_dept, auth.uid(), '{ACTORS["iso_b"]}', v_org_hssb, 'todo', 'low');
    UPDATE _rls_results SET passed = false WHERE case_name = 'tasks.cross_assignee_insert';
  EXCEPTION WHEN OTHERS THEN
    UPDATE _rls_results SET passed = true WHERE case_name = 'tasks.cross_assignee_insert';
  END;

  BEGIN
    INSERT INTO project_members (project_id, profile_id) VALUES (v_project, '{ACTORS["iso_b"]}');
    UPDATE _rls_results SET passed = false WHERE case_name = 'project_members.non_member';
  EXCEPTION WHEN OTHERS THEN
    UPDATE _rls_results SET passed = true WHERE case_name = 'project_members.non_member';
  END;

  BEGIN
    INSERT INTO task_instances (template_id, assignee_profile_id, assignment_date, due_date, status, org_id)
    VALUES (v_template, '{ACTORS["member_a"]}', CURRENT_DATE, now(), 'pending', v_org_b);
    UPDATE _rls_results SET passed = false WHERE case_name = 'instances.cross_template';
  EXCEPTION WHEN OTHERS THEN
    UPDATE _rls_results SET passed = true WHERE case_name = 'instances.cross_template';
  END;

END;
$tests$;

RESET ROLE;
UPDATE _rls_results SET passed = (
  (SELECT COUNT(*) FROM migration_state WHERE key = '011_hssb_profile_backfill') = 1
) WHERE case_name = 'migration_state.rerun_011_marker';

DO $$
DECLARE
  v_fail INT;
  v_pass INT;
  r RECORD;
BEGIN
  SELECT COUNT(*) FILTER (WHERE NOT passed), COUNT(*) FILTER (WHERE passed)
    INTO v_fail, v_pass
  FROM _rls_results;
  IF v_fail > 0 THEN
    FOR r IN SELECT case_name, detail FROM _rls_results WHERE NOT passed LOOP
      RAISE NOTICE 'RLS_MATRIX_FAILURE case=% detail=%', r.case_name, r.detail;
    END LOOP;
  END IF;
  RAISE NOTICE 'RLS_MATRIX_PASS=%', v_pass;
  RAISE NOTICE 'RLS_MATRIX_FAIL=%', v_fail;
  IF v_fail > 0 THEN
    RAISE EXCEPTION 'Independent RLS matrix: % failures', v_fail;
  END IF;
END $$;

ROLLBACK;
"""

OUT.write_text(sql)
print(f"Wrote {OUT} with {len(cases)} cases")
