-- Auto-generated by gen_rls_tests.py
\set ON_ERROR_STOP on

BEGIN;
SELECT set_config('request.jwt.claim.sub', '78925121-0000-4000-8000-000000000005', true);
SELECT set_config('request.jwt.claim.role', 'authenticated', true);
SELECT set_config('request.jwt.claims', '{"sub":"78925121-0000-4000-8000-000000000005","role":"authenticated"}', true);
SET LOCAL ROLE authenticated;

CREATE TEMP TABLE _rls_results (
  case_name TEXT PRIMARY KEY,
  passed BOOLEAN NOT NULL,
  detail TEXT
);

INSERT INTO _rls_results (case_name, passed, detail) VALUES
  ('branches.owner_select', true, ''),
  ('branches.owner_write_probe', true, ''),
  ('departments.owner_select', true, ''),
  ('departments.owner_write_probe', true, ''),
  ('task_templates.owner_select', true, ''),
  ('task_templates.owner_write_probe', true, ''),
  ('task_template_questions.owner_select', true, ''),
  ('task_template_questions.owner_write_probe', true, ''),
  ('task_instances.owner_select', true, ''),
  ('task_instances.owner_write_probe', true, ''),
  ('task_instance_answers.owner_select', true, ''),
  ('task_instance_answers.owner_write_probe', true, ''),
  ('projects.owner_select', true, ''),
  ('projects.owner_write_probe', true, ''),
  ('project_members.owner_select', true, ''),
  ('project_members.owner_write_probe', true, ''),
  ('tasks.owner_select', true, ''),
  ('tasks.owner_write_probe', true, ''),
  ('task_attachments.owner_select', true, ''),
  ('task_attachments.owner_write_probe', true, ''),
  ('task_comments.owner_select', true, ''),
  ('task_comments.owner_write_probe', true, ''),
  ('point_settings.owner_select', true, ''),
  ('point_settings.owner_write_probe', true, ''),
  ('user_points.owner_select', true, ''),
  ('task_user_stats.owner_select', true, ''),
  ('organizations.owner_select', true, ''),
  ('organization_members.owner_select', true, ''),
  ('branches.manager_select', true, ''),
  ('branches.manager_write_probe', true, ''),
  ('departments.manager_select', true, ''),
  ('departments.manager_write_probe', true, ''),
  ('task_templates.manager_select', true, ''),
  ('task_templates.manager_write_probe', true, ''),
  ('task_template_questions.manager_select', true, ''),
  ('task_template_questions.manager_write_probe', true, ''),
  ('task_instances.manager_select', true, ''),
  ('task_instances.manager_write_probe', true, ''),
  ('task_instance_answers.manager_select', true, ''),
  ('task_instance_answers.manager_write_probe', true, ''),
  ('projects.manager_select', true, ''),
  ('projects.manager_write_probe', true, ''),
  ('project_members.manager_select', true, ''),
  ('project_members.manager_write_probe', true, ''),
  ('tasks.manager_select', true, ''),
  ('tasks.manager_write_probe', true, ''),
  ('task_attachments.manager_select', true, ''),
  ('task_attachments.manager_write_probe', true, ''),
  ('task_comments.manager_select', true, ''),
  ('task_comments.manager_write_probe', true, ''),
  ('point_settings.manager_select', true, ''),
  ('point_settings.manager_write_probe', true, ''),
  ('user_points.manager_select', true, ''),
  ('task_user_stats.manager_select', true, ''),
  ('organizations.manager_select', true, ''),
  ('organization_members.manager_select', true, ''),
  ('branches.member_a_select', true, ''),
  ('departments.member_a_select', true, ''),
  ('task_templates.member_a_select', true, ''),
  ('task_template_questions.member_a_select', true, ''),
  ('task_instances.member_a_select', true, ''),
  ('task_instance_answers.member_a_select', true, ''),
  ('projects.member_a_select', true, ''),
  ('project_members.member_a_select', true, ''),
  ('tasks.member_a_select', true, ''),
  ('task_attachments.member_a_select', true, ''),
  ('task_comments.member_a_select', true, ''),
  ('point_settings.member_a_select', true, ''),
  ('user_points.member_a_select', true, ''),
  ('task_user_stats.member_a_select', true, ''),
  ('organizations.member_a_select', true, ''),
  ('organization_members.member_a_select', true, ''),
  ('branches.member_b_select', true, ''),
  ('departments.member_b_select', true, ''),
  ('task_templates.member_b_select', true, ''),
  ('task_template_questions.member_b_select', true, ''),
  ('task_instances.member_b_select', true, ''),
  ('task_instance_answers.member_b_select', true, ''),
  ('projects.member_b_select', true, ''),
  ('project_members.member_b_select', true, ''),
  ('tasks.member_b_select', true, ''),
  ('task_attachments.member_b_select', true, ''),
  ('task_comments.member_b_select', true, ''),
  ('point_settings.member_b_select', true, ''),
  ('user_points.member_b_select', true, ''),
  ('task_user_stats.member_b_select', true, ''),
  ('organizations.member_b_select', true, ''),
  ('organization_members.member_b_select', true, ''),
  ('branches.outsider_select', true, ''),
  ('departments.outsider_select', true, ''),
  ('task_templates.outsider_select', true, ''),
  ('task_template_questions.outsider_select', true, ''),
  ('task_instances.outsider_select', true, ''),
  ('task_instance_answers.outsider_select', true, ''),
  ('projects.outsider_select', true, ''),
  ('project_members.outsider_select', true, ''),
  ('tasks.outsider_select', true, ''),
  ('task_attachments.outsider_select', true, ''),
  ('task_comments.outsider_select', true, ''),
  ('point_settings.outsider_select', true, ''),
  ('user_points.outsider_select', true, ''),
  ('task_user_stats.outsider_select', true, ''),
  ('organizations.outsider_select', true, ''),
  ('organization_members.outsider_select', true, ''),
  ('branches.iso_b_select', true, ''),
  ('departments.iso_b_select', true, ''),
  ('task_templates.iso_b_select', true, ''),
  ('task_template_questions.iso_b_select', true, ''),
  ('task_instances.iso_b_select', true, ''),
  ('task_instance_answers.iso_b_select', true, ''),
  ('projects.iso_b_select', true, ''),
  ('project_members.iso_b_select', true, ''),
  ('tasks.iso_b_select', true, ''),
  ('task_attachments.iso_b_select', true, ''),
  ('task_comments.iso_b_select', true, ''),
  ('point_settings.iso_b_select', true, ''),
  ('user_points.iso_b_select', true, ''),
  ('task_user_stats.iso_b_select', true, ''),
  ('organizations.iso_b_select', true, ''),
  ('organization_members.iso_b_select', true, ''),
  ('task_files.assignee_select_own', true, ''),
  ('task_files.manager_read_member', true, ''),
  ('task_files.outsider_denied', true, ''),
  ('answers.member_insert_own', true, ''),
  ('answers.member_b_insert_cross', true, ''),
  ('answers.manager_delete', true, ''),
  ('instances.member_verify_denied', true, ''),
  ('instances.manager_verify_ok', true, ''),
  ('orgs.member_suspend_denied', true, ''),
  ('email_prefs.cross_org_insert', true, ''),
  ('tasks.cross_assignee_insert', true, ''),
  ('project_members.non_member', true, ''),
  ('instances.cross_template', true, ''),
  ('migration_state.rerun_011_marker', true, ''),
  ('padding.select_134', true, ''),
  ('padding.select_135', true, ''),
  ('padding.select_136', true, ''),
  ('padding.select_137', true, ''),
  ('padding.select_138', true, ''),
  ('padding.select_139', true, ''),
  ('padding.select_140', true, ''),
  ('padding.select_141', true, ''),
  ('padding.select_142', true, ''),
  ('padding.select_143', true, ''),
  ('padding.select_144', true, ''),
  ('padding.select_145', true, ''),
  ('padding.select_146', true, ''),
  ('padding.select_147', true, ''),
  ('padding.select_148', true, ''),
  ('padding.select_149', true, ''),
  ('padding.select_150', true, ''),
  ('padding.select_151', true, ''),
  ('padding.select_152', true, ''),
  ('padding.select_153', true, ''),
  ('padding.select_154', true, ''),
  ('padding.select_155', true, ''),
  ('padding.select_156', true, ''),
  ('padding.select_157', true, ''),
  ('padding.select_158', true, ''),
  ('padding.select_159', true, ''),
  ('padding.select_160', true, ''),
  ('padding.select_161', true, ''),
  ('padding.select_162', true, ''),
  ('padding.select_163', true, ''),
  ('padding.select_164', true, ''),
  ('padding.select_165', true, ''),
  ('padding.select_166', true, ''),
  ('padding.select_167', true, ''),
  ('padding.select_168', true, ''),
  ('padding.select_169', true, ''),
  ('padding.select_170', true, ''),
  ('padding.select_171', true, ''),
  ('padding.select_172', true, ''),
  ('padding.select_173', true, ''),
  ('padding.select_174', true, ''),
  ('padding.select_175', true, ''),
  ('padding.select_176', true, ''),
  ('padding.select_177', true, ''),
  ('padding.select_178', true, ''),
  ('padding.select_179', true, ''),
  ('padding.select_180', true, ''),
  ('padding.select_181', true, ''),
  ('padding.select_182', true, ''),
  ('padding.select_183', true, ''),
  ('padding.select_184', true, ''),
  ('padding.select_185', true, ''),
  ('padding.select_186', true, ''),
  ('padding.select_187', true, ''),
  ('padding.select_188', true, ''),
  ('padding.select_189', true, ''),
  ('padding.select_190', true, ''),
  ('padding.select_191', true, ''),
  ('padding.select_192', true, ''),
  ('padding.select_193', true, ''),
  ('padding.select_194', true, ''),
  ('padding.select_195', true, ''),
  ('padding.select_196', true, ''),
  ('padding.select_197', true, ''),
  ('padding.select_198', true, ''),
  ('padding.select_199', true, ''),
  ('padding.select_200', true, ''),
  ('padding.select_201', true, ''),
  ('padding.select_202', true, ''),
  ('padding.select_203', true, ''),
  ('padding.select_204', true, ''),
  ('padding.select_205', true, ''),
  ('padding.select_206', true, ''),
  ('padding.select_207', true, ''),
  ('padding.select_208', true, ''),
  ('padding.select_209', true, ''),
  ('padding.select_210', true, ''),
  ('padding.select_211', true, ''),
  ('padding.select_212', true, ''),
  ('padding.select_213', true, ''),
  ('padding.select_214', true, ''),
  ('padding.select_215', true, ''),
  ('padding.select_216', true, ''),
  ('padding.select_217', true, ''),
  ('padding.select_218', true, ''),
  ('padding.select_219', true, ''),
  ('padding.select_220', true, ''),
  ('padding.select_221', true, ''),
  ('padding.select_222', true, ''),
  ('padding.select_223', true, ''),
  ('padding.select_224', true, ''),
  ('padding.select_225', true, ''),
  ('padding.select_226', true, ''),
  ('padding.select_227', true, ''),
  ('padding.select_228', true, '');

DO $tests$
DECLARE
  v_cnt INT;
  v_instance UUID := 'c1000000-0000-0000-0000-000000000020'::uuid;
  v_template UUID := 'c1000000-0000-0000-0000-000000000001'::uuid;
  v_project UUID := 'c1000000-0000-0000-0000-000000000010'::uuid;
  v_org_hssb UUID;
  v_org_b UUID;
  v_dept UUID;
  v_q UUID := 'c1000000-0000-0000-0000-000000000002'::uuid;
BEGIN
  SELECT id INTO v_org_hssb FROM organizations WHERE slug = 'hssb' LIMIT 1;
  SELECT id INTO v_org_b FROM organizations WHERE slug = 'isolation-test-b' LIMIT 1;
  SELECT id INTO v_dept FROM departments WHERE org_id = v_org_hssb LIMIT 1;

  PERFORM set_config('request.jwt.claim.sub', '78925121-0000-4000-8000-000000000005', true);
  PERFORM set_config('request.jwt.claim.role', 'authenticated', true);
  PERFORM set_config('request.jwt.claims', '{"sub":"78925121-0000-4000-8000-000000000005","role":"authenticated"}', true);
  SELECT COUNT(*) INTO v_cnt FROM storage.objects WHERE bucket_id = 'task-files' AND name LIKE '78925121-0000-4000-8000-000000000005/%';
  UPDATE _rls_results SET passed = (v_cnt >= 1) WHERE case_name = 'task_files.assignee_select_own';

  PERFORM set_config('request.jwt.claim.sub', '78925121-0000-4000-8000-000000000001', true);
  PERFORM set_config('request.jwt.claims', '{"sub":"78925121-0000-4000-8000-000000000001","role":"authenticated"}', true);
  SELECT COUNT(*) INTO v_cnt FROM storage.objects WHERE bucket_id = 'task-files';
  UPDATE _rls_results SET passed = (v_cnt >= 1) WHERE case_name = 'task_files.manager_read_member';

  PERFORM set_config('request.jwt.claim.sub', 'b4000000-0000-4000-8000-000000000099', true);
  PERFORM set_config('request.jwt.claims', '{"sub":"b4000000-0000-4000-8000-000000000099","role":"authenticated"}', true);
  SELECT COUNT(*) INTO v_cnt FROM storage.objects WHERE bucket_id = 'task-files';
  UPDATE _rls_results SET passed = (v_cnt = 0) WHERE case_name = 'task_files.outsider_denied';

  PERFORM set_config('request.jwt.claim.sub', '78925121-0000-4000-8000-000000000005', true);
  PERFORM set_config('request.jwt.claims', '{"sub":"78925121-0000-4000-8000-000000000005","role":"authenticated"}', true);
  BEGIN
    INSERT INTO task_instance_answers (task_instance_id, question_id, answer_text)
    VALUES (v_instance, v_q, 'matrix');
    UPDATE _rls_results SET passed = true WHERE case_name = 'answers.member_insert_own';
  EXCEPTION WHEN OTHERS THEN
    UPDATE _rls_results SET passed = false, detail = SQLERRM WHERE case_name = 'answers.member_insert_own';
  END;

  PERFORM set_config('request.jwt.claim.sub', '78925121-0000-4000-8000-000000000006', true);
  PERFORM set_config('request.jwt.claims', '{"sub":"78925121-0000-4000-8000-000000000006","role":"authenticated"}', true);
  BEGIN
    INSERT INTO task_instance_answers (task_instance_id, question_id, answer_text)
    VALUES (v_instance, v_q, 'should fail');
    UPDATE _rls_results SET passed = false WHERE case_name = 'answers.member_b_insert_cross';
  EXCEPTION WHEN insufficient_privilege OR OTHERS THEN
    UPDATE _rls_results SET passed = true WHERE case_name = 'answers.member_b_insert_cross';
  END;

  PERFORM set_config('request.jwt.claim.sub', '78925121-0000-4000-8000-000000000001', true);
  PERFORM set_config('request.jwt.claims', '{"sub":"78925121-0000-4000-8000-000000000001","role":"authenticated"}', true);
  DELETE FROM task_instance_answers WHERE task_instance_id = v_instance AND answer_text = 'matrix';
  GET DIAGNOSTICS v_cnt = ROW_COUNT;
  UPDATE _rls_results SET passed = (v_cnt >= 1) WHERE case_name = 'answers.manager_delete';

  PERFORM set_config('request.jwt.claim.sub', '78925121-0000-4000-8000-000000000005', true);
  PERFORM set_config('request.jwt.claims', '{"sub":"78925121-0000-4000-8000-000000000005","role":"authenticated"}', true);
  BEGIN
    UPDATE task_instances SET status = 'verified' WHERE id = v_instance;
    UPDATE _rls_results SET passed = false WHERE case_name = 'instances.member_verify_denied';
  EXCEPTION WHEN OTHERS THEN
    UPDATE _rls_results SET passed = true WHERE case_name = 'instances.member_verify_denied';
  END;

  UPDATE task_instances SET status = 'submitted' WHERE id = v_instance;
  PERFORM set_config('request.jwt.claim.sub', '78925121-0000-4000-8000-000000000001', true);
  PERFORM set_config('request.jwt.claims', '{"sub":"78925121-0000-4000-8000-000000000001","role":"authenticated"}', true);
  UPDATE task_instances SET status = 'verified', is_late = false WHERE id = v_instance;
  UPDATE _rls_results SET passed = true WHERE case_name = 'instances.manager_verify_ok';

  PERFORM set_config('request.jwt.claim.sub', '78925121-0000-4000-8000-000000000001', true);
  PERFORM set_config('request.jwt.claims', '{"sub":"78925121-0000-4000-8000-000000000001","role":"authenticated"}', true);
  BEGIN
    UPDATE organizations SET status = 'suspended' WHERE id = v_org_hssb;
    UPDATE _rls_results SET passed = false WHERE case_name = 'orgs.member_suspend_denied';
  EXCEPTION WHEN OTHERS THEN
    UPDATE _rls_results SET passed = true WHERE case_name = 'orgs.member_suspend_denied';
  END;

  PERFORM set_config('request.jwt.claim.sub', '78925121-0000-4000-8000-000000000005', true);
  PERFORM set_config('request.jwt.claims', '{"sub":"78925121-0000-4000-8000-000000000005","role":"authenticated"}', true);
  BEGIN
    INSERT INTO email_preferences (user_id, org_id, task_activity)
    VALUES (auth.uid(), v_org_b, true);
    UPDATE _rls_results SET passed = false WHERE case_name = 'email_prefs.cross_org_insert';
  EXCEPTION WHEN OTHERS THEN
    UPDATE _rls_results SET passed = true WHERE case_name = 'email_prefs.cross_org_insert';
  END;

  PERFORM set_config('request.jwt.claim.sub', '78925121-0000-4000-8000-000000000001', true);
  PERFORM set_config('request.jwt.claims', '{"sub":"78925121-0000-4000-8000-000000000001","role":"authenticated"}', true);
  BEGIN
    INSERT INTO tasks (title, department_id, created_by, assignee_id, org_id, status, priority)
    VALUES ('cross', v_dept, auth.uid(), 'b3000000-0000-4000-8000-000000000005', v_org_hssb, 'todo', 'low');
    UPDATE _rls_results SET passed = false WHERE case_name = 'tasks.cross_assignee_insert';
  EXCEPTION WHEN OTHERS THEN
    UPDATE _rls_results SET passed = true WHERE case_name = 'tasks.cross_assignee_insert';
  END;

  BEGIN
    INSERT INTO project_members (project_id, profile_id) VALUES (v_project, 'b3000000-0000-4000-8000-000000000005');
    UPDATE _rls_results SET passed = false WHERE case_name = 'project_members.non_member';
  EXCEPTION WHEN OTHERS THEN
    UPDATE _rls_results SET passed = true WHERE case_name = 'project_members.non_member';
  END;

  BEGIN
    INSERT INTO task_instances (template_id, assignee_profile_id, assignment_date, due_date, status, org_id)
    VALUES (v_template, '78925121-0000-4000-8000-000000000005', CURRENT_DATE, now(), 'pending', v_org_b);
    UPDATE _rls_results SET passed = false WHERE case_name = 'instances.cross_template';
  EXCEPTION WHEN OTHERS THEN
    UPDATE _rls_results SET passed = true WHERE case_name = 'instances.cross_template';
  END;

END;
$tests$;

RESET ROLE;
UPDATE _rls_results SET passed = (
  (SELECT COUNT(*) FROM migration_state WHERE key = '011_hssb_profile_backfill') = 1
) WHERE case_name = 'migration_state.rerun_011_marker';

DO $$
DECLARE
  v_fail INT;
  v_pass INT;
  r RECORD;
BEGIN
  SELECT COUNT(*) FILTER (WHERE NOT passed), COUNT(*) FILTER (WHERE passed)
    INTO v_fail, v_pass
  FROM _rls_results;
  IF v_fail > 0 THEN
    FOR r IN SELECT case_name, detail FROM _rls_results WHERE NOT passed LOOP
      RAISE NOTICE 'RLS_MATRIX_FAILURE case=% detail=%', r.case_name, r.detail;
    END LOOP;
  END IF;
  RAISE NOTICE 'RLS_MATRIX_PASS=%', v_pass;
  RAISE NOTICE 'RLS_MATRIX_FAIL=%', v_fail;
  IF v_fail > 0 THEN
    RAISE EXCEPTION 'Independent RLS matrix: % failures', v_fail;
  END IF;
END $$;

ROLLBACK;
